version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: Europe/Dublin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.68
    - 8.10.71
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: npm
    versions:
    - 6.14.10
  - dependency-name: commitizen
    versions:
    - 4.2.2
  - dependency-name: typescript
    versions:
    - 3.9.7
  - dependency-name: handlebars
    versions:
    - 4.7.6
